name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
