name: 'build-test'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github_token: ${{ secrets.TOKEN }}
          task_url_pattern: 'https://youtrack.domain.com/youtrack/issue/{{task_number}}'
          task_url_placeholder: '{{task_number}}'
          task_number_regexp: 'TASK-\d+'